In [49]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDClassifier
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import confusion_matrix

In [59]:
# data = pd.read_csv("data.csv", header = None, names = ['No.','Tweet','#Number', 'MedicalRelevance', 'X', 'Status','Unnamed'])
data = pd.read_csv("data1.csv", header = None, names = ['No.','Tweet','#Number', 'MedicalRelevance', 'X', 'Status','Unnamed'])

In [60]:
data.head()

No.                                              Tweet   #Number  \
0   NaN                                         Tweet Text  # number   
1  10.0  As people‰Û¡ÌÝåÁÌÎ̴̝åÈs anger boils over in ...       343   
2  14.0  Peacock tears get eggs. Eating Mangoes get bab...       246   
3  22.0  Listen. An isotope of uranium ore called Actin...       160   
4  24.0  Watching a 29 year old woman with stage 4 ovar...       137   

    MedicalRelevance                               X              Status  \
0  Medical relevance                               X  Does X cure cancer   
1                yes                         aspirin                  no   
2                yes                       cow urine                  no   
3                yes                   actinium -225                 yes   
4                yes  Gerson Therapy, MMS, Pharma Dr                 yes   

                                             Unnamed  
0                                         Unnamed: 5  
1                                                NaN  
2  similarly eita te Whatsapp University lekha. K...  
3                                                NaN  
4                                                NaN

In [61]:
data.loc[data["Status"]=='yes',"Status"] = 1
data.loc[data["Status"]=='no',"Status"] = 0

data.loc[data["MedicalRelevance"]=='yes',"MedicalRelevance"] = 1
data.loc[data["MedicalRelevance"]=='no',"MedicalRelevance"] = 0

In [62]:
data = data[1:]
data.head()

No.                                              Tweet #Number  \
1  10.0  As people‰Û¡ÌÝåÁÌÎ̴̝åÈs anger boils over in ...     343   
2  14.0  Peacock tears get eggs. Eating Mangoes get bab...     246   
3  22.0  Listen. An isotope of uranium ore called Actin...     160   
4  24.0  Watching a 29 year old woman with stage 4 ovar...     137   
5  26.0  @iamsonalibendre Hope you know there are very ...     133   

  MedicalRelevance                               X Status  \
1                1                         aspirin      0   
2                1                       cow urine      0   
3                1                   actinium -225      1   
4                1  Gerson Therapy, MMS, Pharma Dr      1   
5                1                   urine therapy      0   

                                             Unnamed  
1                                                NaN  
2  similarly eita te Whatsapp University lekha. K...  
3                                                NaN  
4                                                NaN  
5                                                NaN

In [63]:
data_x = data["Tweet"]
X = data["#Number"]
data_y = data["Status"]
data_mr_y = data["MedicalRelevance"]

In [64]:
tfidf = TfidfVectorizer(min_df = 1, stop_words = 'english')

In [69]:
for i in range(1,20):
    x_train, x_test, y_train, y_test = train_test_split(data_x, data_y,test_size = 0.05*i, random_state = 42 )
#     x_train, x_test, y_train, y_test = train_test_split(data_x, data_mr_y,test_size = 0.05*i, random_state = 42 )
    x_train_tfidf = tfidf.fit_transform(x_train)
    mnb = MultinomialNB()
    y_train = y_train.astype('int')
    mnb.fit(x_train_tfidf, y_train)
    x_test_tfidf = tfidf.transform(x_test)
    pred = mnb.predict(x_test_tfidf)
    actual = np.array(y_test)
    count = 0
    for i in range(len(pred)):
        if pred[i]==actual[i]:
            count = count +1
    from sklearn.metrics import confusion_matrix
    print (confusion_matrix(np.array(y_test).astype('int'), mnb.predict(x_test_tfidf)),"\n\n")
#     print (confusion_matrix(np.array(y_train).astype('int'), mnb.predict(x_train_tfidf)),"\n\n")

[[3 4]
 [1 8]] 


[[ 5  8]
 [ 2 16]] 


[[ 9 13]
 [ 2 22]] 


[[12 17]
 [ 4 28]] 


[[14 23]
 [ 4 35]] 


[[14 29]
 [ 5 43]] 


[[16 35]
 [ 5 50]] 


[[18 39]
 [ 6 58]] 


[[19 45]
 [ 8 64]] 


[[20 53]
 [ 4 74]] 


[[24 53]
 [ 9 81]] 


[[22 61]
 [ 8 91]] 


[[ 19  71]
 [  4 103]] 


[[ 18  79]
 [  3 112]] 


[[ 24  77]
 [  6 120]] 


[[ 12  97]
 [  0 133]] 


[[ 13 102]
 [  1 141]] 


[[  9 112]
 [  0 151]] 


[[ 14 111]
 [  2 160]] 




SyntaxError: unexpected EOF while parsing (<ipython-input-64-5606e2934ab9>, line 1)

In [17]:
mnb = MultinomialNB()

In [18]:
y_train = y_train.astype('int')

In [19]:
mnb.fit(x_train_tfidf, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [20]:
x_test_tfidf = tfidf.transform(x_test)

In [21]:
pred = mnb.predict(x_test_tfidf)

In [22]:
actual = np.array(y_test)

In [23]:
count = 0
for i in range(len(pred)):
    if pred[i]==actual[i]:
        count = count +1

In [24]:
count/len(pred)

0.930952380952381

In [25]:
count

391

In [27]:
np.sum(y_train == 0)

1536

In [28]:
np.sum(y_train == 1)

143

In [35]:
from sklearn.metrics import confusion_matrix
confusion_matrix(np.array(y_train), mnb.predict(x_train_tfidf))

array([[1536,    0],
       [ 135,    8]])

In [26]:
# Training Support Vector Machines - SVM and calculating its performance

#tfidf_transformer = TfidfTransformer()
text_clf_svm = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                         ('clf-svm', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, n_iter=5, random_state=42))])

text_clf_svm = text_clf_svm.fit(x_train, y_train)
predicted_svm = text_clf_svm.predict(x_test)
np.mean(predicted_svm == y_test)

/Applications/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


0.9333333333333333